Grab the external IP and resolve to ipv4

diff --git a/.github/workflows/cicdpipeline.yml b/.github/workflows/cicdpipeline.yml
--- a/.github/workflows/cicdpipeline.yml
+++ b/.github/workflows/cicdpipeline.yml
@@ -161,21 +161,24 @@ jobs:
           echo "Getting Kubernetes pods..."
           kubectl get pods -o wide --all-namespaces   
     
-    - name: Get external IP for service
-      id: get_external
+    - name: Get External IP
+      id: get_external_ip
       run: |
           EXTERNAL_IP=$(kubectl get svc gab-app-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
           echo "EXTERNAL_IP=$EXTERNAL_IP" >> $GITHUB_ENV
-   
-    - name: Output External IP
-      run: echo "External IP is ${{ env.EXTERNAL_IP }}"
-    
+          echo "External IP is $EXTERNAL_IP"
+
     - name: Resolve External IP to IPv4
       id: resolve_ip
       run: |
-          # Use dig to resolve the external IP
+          echo "Resolving external IP to IPv4..."
           IPV4_ADDR=$(dig +short ${{ env.EXTERNAL_IP }})
-          echo "IPV4_ADDR=$IPV4_ADDR" >> $GITHUB_ENV
-   
+          if [ -z "$IPV4_ADDR" ]; then
+            echo "Error: Unable to resolve external IP to IPv4"
+            exit 1
+          else
+            echo "IPV4_ADDR=$IPV4_ADDR" >> $GITHUB_ENV
+          fi
+
     - name: Output IPv4 Address
       run: echo "IPv4 Address is ${{ env.IPV4_ADDR }}"
