Added node describe for dynamic env dev or prod

diff --git a/.github/workflows/cicdpipeline.yml b/.github/workflows/cicdpipeline.yml
--- a/.github/workflows/cicdpipeline.yml
+++ b/.github/workflows/cicdpipeline.yml
@@ -164,26 +164,30 @@ jobs:
       run: |
           echo "Getting Kubernetes pods..."
           kubectl get pods -o wide --all-namespaces   
+    - name: Describe Kubernetes Nodes
+      run: | 
+          echo "Getting Kubernetes nodes details"
+          kubectl describe node -l environment=${{ env.ENVIRONMENT }
     
-    - name: Get External IP
-      id: get_external_ip
-      run: |
-          EXTERNAL_IP=$(kubectl get svc gab-app-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
-          echo "EXTERNAL_IP=$EXTERNAL_IP"
-          echo "External IP is $EXTERNAL_IP"
+    # - name: Get External IP
+    #   id: get_external_ip
+    #   run: |
+    #       EXTERNAL_IP=$(kubectl get svc gab-app-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
+    #       echo "EXTERNAL_IP=$EXTERNAL_IP"
+    #       echo "External IP is $EXTERNAL_IP"
 
-    - name: Resolve External IP to IPv4
-      id: resolve_ip
-      run: |
-          echo "Resolving external IP to IPv4..."
-          IPV4_ADDR=$(dig +short $EXTERNAL_IP)
-          if [ -z "$IPV4_ADDR" ]; then
-            echo "Error: Unable to resolve external IP to IPv4"
-            exit 1
-          else
-            echo "IPV4_ADDR=$IPV4_ADDR"
-            echo "Resolved IPv4 Address is $IPV4_ADDR"
-          fi
+    # - name: Resolve External IP to IPv4
+    #   id: resolve_ip
+    #   run: |
+    #       echo "Resolving external IP to IPv4..."
+    #       IPV4_ADDR=$(dig +short $EXTERNAL_IP)
+    #       if [ -z "$IPV4_ADDR" ]; then
+    #         echo "Error: Unable to resolve external IP to IPv4"
+    #         exit 1
+    #       else
+    #         echo "IPV4_ADDR=$IPV4_ADDR"
+    #         echo "Resolved IPv4 Address is $IPV4_ADDR"
+    #       fi
 
-    - name: Output IPv4 Address
-      run: echo "IPv4 Address is ${{ env.IPV4_ADDR }}"
+    # - name: Output IPv4 Address
+    #   run: echo "IPv4 Address is ${{ env.IPV4_ADDR }}"
